version: '3.8'

services:
  web:
    build: .
    container_name: vegan-bulletin
    command: /app/docker-entrypoint.sh
    volumes:
      # Media files (user uploads)
      # Override with MEDIA_PATH env var for absolute paths (e.g., NAS deployments)
      - ${MEDIA_PATH:-./media}:/app/media
      # Static files (CSS, JS)
      # Override with STATIC_PATH env var for absolute paths
      - ${STATIC_PATH:-./staticfiles}:/app/staticfiles
      # Database file
      # Override with DB_PATH env var for absolute paths
      - ${DB_PATH:-./db.sqlite3}:/app/db.sqlite3
    ports:
      # Map to host port - customize with HOST_PORT in .env
      # Default: 8000, NAS example: 9040
      - "${HOST_PORT:-8000}:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CITY_NAME=${CITY_NAME:-Chicago}
      - CITY_STATE=${CITY_STATE:-IL}
      - CITY_TIMEZONE=${CITY_TIMEZONE:-America/Chicago}
      - CONTACT_EMAIL=${CONTACT_EMAIL:-chicagoveganbulletin@gmail.com}
      - DATABASE_NAME=${DATABASE_NAME:-db.sqlite3}
      - DATABASE_PATH=${DATABASE_PATH:-default}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
